title: Paradigms to Practice
description: An aspiring cognitive scientist's digital garden tracking the journey from theory to implementation
baseurl: "/paradigms-to-practice"
url: "https://SamBitSync.github.io"
github_username: SamBitSync

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:name
  htdp:
    output: true
    permalink: /:collection/:name
  pybites:
    output: true
    permalink: /:collection/:name
  downey-books:
    output: true
    permalink: /:collection/:name
  testing:
    output: true
    permalink: /:collection/:name
  datascience:
    output: true
    permalink: /:collection/:name
  cogsci-projects:
    output: true
    permalink: /:collection/:name

# Navigation
header_pages:
  - learning-tracks/index.md
  - research-methods/index.md
  - cogsci-projects/index.md
  - tools/index.md

# Defaults for collections
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Aspiring Cognitive Scientist"
  - scope:
      path: ""
      type: "htdp"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "pybites"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "downey-books"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "testing"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "datascience"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "cogsci-projects"
    values:
      layout: "page"