title: Paradigms to Practice
description: An aspiring cognitive scientist's digital garden tracking the journey from theory to implementation
baseurl: "/paradigms-to-practice"
url: "https://SamBitSync.github.io"
github_username: SamBitSync

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:name
  htdp:
    output: true
    permalink: /:collection/:name
  pybites:  # Changed from python
    output: true
    permalink: /:collection/:name
  downey-books:  # Changed from downey
    output: true
    permalink: /:collection/:name
  testing:
    output: true
    permalink: /:collection/:name
  datascience:
    output: true
    permalink: /:collection/:name
  cogsci-projects:  # Changed from cogsci
    output: true
    permalink: /:collection/:name

# Defaults for collections
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Aspiring Cognitive Scientist"
  - scope:
      path: ""
      type: "htdp"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "python"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "downey"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "testing"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "datascience"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "cogsci"
    values:
      layout: "page"